package libusbone;
/**
 * \ingroup asyncio<br>
 * Isochronous packet descriptor.<br>
 * <i>native declaration : /usr/include/limits.h:652</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libusb_iso_packet_descriptor extends com.sun.jna.Structure {
	/// Length of data to request in this packet
	public int length;
	/// Amount of data that was actually transferred
	public int actual_length;
	/**
	 * Status code for this packet<br>
	 * @see libusb_transfer_status<br>
	 * C type : libusb_transfer_status
	 */
	public int status;
	public libusb_iso_packet_descriptor() {
		super();
	}
	/**
	 * @param length Length of data to request in this packet<br>
	 * @param actual_length Amount of data that was actually transferred<br>
	 * @param status Status code for this packet<br>
	 * @see libusb_transfer_status<br>
	 * C type : libusb_transfer_status
	 */
	public libusb_iso_packet_descriptor(int length, int actual_length, int status) {
		super();
		this.length = length;
		this.actual_length = actual_length;
		this.status = status;
	}
	protected ByReference newByReference() {
		ByReference s = new ByReference();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected ByValue newByValue() {
		ByValue s = new ByValue();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected libusb_iso_packet_descriptor newInstance() {
		libusb_iso_packet_descriptor s = new libusb_iso_packet_descriptor();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	public static class ByReference extends libusb_iso_packet_descriptor implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends libusb_iso_packet_descriptor implements com.sun.jna.Structure.ByValue {}
}
